INSERT INTO CUSTOMER(CUSTOMER_ID, FIRST_NAME, LAST_NAME, ACTIVE, PASSWORD, MOBILE_NO) VALUES(1,'AVINASH','MOLAJ',  TRUE, 'AVINASH', '12345678990');
INSERT INTO CUSTOMER(CUSTOMER_ID, FIRST_NAME, LAST_NAME, ACTIVE, PASSWORD, MOBILE_NO) VALUES(2,'AVINASH','MOLAJ',  TRUE, 'AVINASH', '12345678990');
INSERT INTO CUSTOMER(CUSTOMER_ID, FIRST_NAME, LAST_NAME, ACTIVE, PASSWORD, MOBILE_NO) VALUES(3,'AVINASH','MOLAJ',  TRUE, 'AVINASH', '12345678990');
INSERT INTO CUSTOMER(CUSTOMER_ID, FIRST_NAME, LAST_NAME, ACTIVE, PASSWORD, MOBILE_NO) VALUES(4,'AVINASH','MOLAJ',  TRUE, 'AVINASH', '12345678990');
INSERT INTO CUSTOMER(CUSTOMER_ID, FIRST_NAME, LAST_NAME, ACTIVE, PASSWORD, MOBILE_NO) VALUES(5,'AVINASH','MOLAJ',  TRUE, 'AVINASH', '12345678990');
