INSERT INTO CUSTOMER(CUSTOMER_ID, FIRST_NAME, LAST_NAME, ACTIVE, PASSWORD, EMAIL, MOBILE_NO) VALUES(1,'AVINASH','MOLAJ',  TRUE, 'AVINASH', 'AVINASH@GMAIL', '12345678990');
INSERT INTO CUSTOMER(CUSTOMER_ID, FIRST_NAME, LAST_NAME, ACTIVE, PASSWORD, EMAIL, MOBILE_NO) VALUES(2,'DIPAK','BALSANTOSH',  TRUE, 'DIPAK', 'DIPAK@GMAIL', '0123456789');
INSERT INTO CUSTOMER(CUSTOMER_ID, FIRST_NAME, LAST_NAME, ACTIVE, PASSWORD, EMAIL, MOBILE_NO) VALUES(3,'NISARG','TURKE',  FALSE, 'NISARG', 'NISARG@GMAIL', '1221112121');
INSERT INTO CUSTOMER(CUSTOMER_ID, FIRST_NAME, LAST_NAME, ACTIVE, PASSWORD, EMAIL, MOBILE_NO) VALUES(4,'GAURAV','SONAWANE',  TRUE, 'GAURAV', 'GAURAV@GMAIL','8877665544');
INSERT INTO CUSTOMER(CUSTOMER_ID, FIRST_NAME, LAST_NAME, ACTIVE, PASSWORD, EMAIL, MOBILE_NO) VALUES(5,'MRUNMAYI','DHARMADHIKARI',  TRUE, 'MRUNMAYI', 'MRUNMAYI@GMAIL','1122334455');

INSERT INTO Dvd(FILM_ID, TITLE, DESCRIPTION, RENTAL_DURATION, RENTAL_RATE, RATING, GENRE, LANGUAGE, DIRECTOR, ACTOR, YEAR) VALUES(1,'DDLJ','ROMANCE MOVIE', 2, 100, 4.5, 'THRILLER', 'HINDI', 'SS', 'SHAHRUKH KHAN', 2010);
INSERT INTO Dvd(FILM_ID, TITLE, DESCRIPTION, RENTAL_DURATION, RENTAL_RATE, RATING, GENRE, LANGUAGE, DIRECTOR, ACTOR, YEAR) VALUES(2,'ABCD','DANCE MOVIE', 5, 200, 3.5, 'HORROR', 'HINDI', 'SS', 'VARUN DHAVAN', 2011);
INSERT INTO Dvd(FILM_ID, TITLE, DESCRIPTION, RENTAL_DURATION, RENTAL_RATE, RATING, GENRE, LANGUAGE, DIRECTOR, ACTOR, YEAR) VALUES(3,'ABCD2','DANCE MOVIE', 10, 300, 4.4, 'THRILLER', 'HINDI', 'SS', 'VARUN DHAVAN', 2013);
INSERT INTO Dvd(FILM_ID, TITLE, DESCRIPTION, RENTAL_DURATION, RENTAL_RATE, RATING, GENRE, LANGUAGE, DIRECTOR, ACTOR, YEAR) VALUES(4,'SINGHAM','ACTION MOVIE', 13, 400, 3.5, 'THRILLER', 'HINDI', 'SS', 'AJAY DEVGAN', 2014);
INSERT INTO Dvd(FILM_ID, TITLE, DESCRIPTION, RENTAL_DURATION, RENTAL_RATE, RATING, GENRE, LANGUAGE, DIRECTOR, ACTOR, YEAR) VALUES(5,'HERA PHERI','COMEDY MOVIE', 12, 500, 5.0, 'COMEDY', 'HINDI', 'SS', 'PARSH RAVAL', 2015);